[workspace.package]
description = "Download stickers from telegram "
authors = ["mslxl <i@mslxl.com>"]
version = "0.0.1"
edition = "2021"
license = "MIT"
repository = "https://github.com/mslxl/tstickers-rs"

[workspace]
resolver = "2"

members = [
    "tsticker",
    "cli"
]
